spring.application.name=task
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/profile_db
spring.datasource.username=postgres
spring.datasource.password=2001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.security.oauth2.client.registration.google.client-id=749029125273-be9k7l2s2j4shlsfjn4gejtae0o6rhha.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
